"use client";

import type { ReactNode } from "react";
import { ArrowLeft, CheckCircle2, Clock3, Coins, LayoutDashboard, MoreHorizontal, Shield, Target, TrendingUp, Users, XCircle, Zap } from "lucide-react";
import { motion } from "framer-motion";
import type { ChildSnapshot, ParentOverviewMetrics } from "@/types/domain";
import { BrandMark } from "@/components/brand-mark";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { SectionHeading } from "@/components/section-heading";

function Metric({ icon, label, value, detail, tone }: { icon: ReactNode; label: string; value: string; detail: string; tone: string }) {
  return <Card className="p-4"><div className="mb-4 flex items-center justify-between"><div className={`grid size-9 place-items-center rounded-xl ${tone}`}>{icon}</div><MoreHorizontal size={17} className="text-slate-600" /></div><p className="text-2xl font-black text-white">{value}</p><p className="mt-1 text-xs font-bold text-slate-400">{label}</p><p className="mt-3 text-[10px] text-slate-500">{detail}</p></Card>;
}

export function ParentDashboard({ childList, metrics, demoMode, onBack }: { childList: ChildSnapshot[]; metrics: ParentOverviewMetrics; demoMode: boolean; onBack: () => void }) {
  const familyXp = childList.reduce((sum, child) => sum + child.totalXp, 0);
  const familyCoins = childList.reduce((sum, child) => sum + child.coins, 0);
  return <main className="mx-auto min-h-screen w-full max-w-7xl px-4 pb-10 sm:px-8">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 py-5"><div className="flex items-center gap-5"><BrandMark /><div className="hidden h-7 w-px bg-white/10 md:block" /><div className="hidden md:block"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Painel da base</p><p className="text-sm font-bold text-white">Visão geral da família</p></div></div><Button variant="outline" size="sm" onClick={onBack}><ArrowLeft size={15} /> Trocar perfil</Button></header>
    <section className="py-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-yellow-200"><LayoutDashboard size={14} /> Central de comando</p><h1 className="text-3xl font-black tracking-[-.04em] text-white sm:text-4xl">A base está evoluindo.</h1><p className="mt-2 text-sm text-slate-400">Acompanhe o ritmo das missões e celebre cada avanço.</p></div><Badge className="border-cyan-300/20 bg-cyan-300/10 text-cyan-200">{demoMode ? "Dados de demonstração" : "Neon conectado"}</Badge></div>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={<TrendingUp size={17} />} label="Taxa diária" value={`${metrics.dailyCompletion}%`} detail={`${metrics.totalMissions} missão(ões) hoje`} tone="bg-emerald-300/10 text-emerald-300" /><Metric icon={<Target size={17} />} label="Missões ativas" value={String(metrics.activeMissions)} detail={`${metrics.weeklyCompletion}% nos últimos 7 dias`} tone="bg-purple-300/10 text-purple-200" /><Metric icon={<Clock3 size={17} />} label="Aguardando" value={String(metrics.pendingApprovals)} detail={metrics.pendingApprovals ? "Precisam da sua revisão" : "Tudo revisado por enquanto"} tone="bg-yellow-300/10 text-yellow-200" /><Metric icon={<XCircle size={17} />} label="Atrasadas" value={String(metrics.overdueMissions)} detail={metrics.overdueMissions ? "Requer atenção" : "Nenhuma pendência atrasada"} tone="bg-rose-300/10 text-rose-300" /></div>
    </section>
    <section className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><div><SectionHeading eyebrow="Progresso individual" title="Guardiões da base" action={<button type="button" className="text-xs font-bold text-cyan-300">Gerenciar <span className="hidden sm:inline">perfis</span> →</button>} /><div className="grid gap-3 sm:grid-cols-2">{childList.map((child, index) => <motion.div key={child.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .08 }}><ChildAdminCard child={child} /></motion.div>)}</div></div><div><SectionHeading eyebrow="Ação necessária" title="Fila de aprovação" /><Card className="divide-y divide-white/10 overflow-hidden">{childList.flatMap((child) => child.missions.filter((mission) => mission.status === "waiting_approval").map((mission) => <div key={mission.id} className="flex items-center gap-3 p-4"><div className="grid size-10 place-items-center rounded-xl bg-yellow-300/10 text-yellow-200"><CheckCircle2 size={18} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-white">{mission.title}</p><p className="text-xs text-slate-500">{child.displayName} • +{mission.xp} XP</p></div><button type="button" aria-label={`Aprovar ${mission.title}`} className="grid size-9 place-items-center rounded-xl bg-emerald-300/10 text-emerald-300"><CheckCircle2 size={16} /></button></div>))}{demoMode && <div className="flex items-center gap-3 p-4"><div className="grid size-10 place-items-center rounded-xl bg-purple-300/10 text-purple-200"><Coins size={18} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-white">Noite do filme</p><p className="text-xs text-slate-500">Jennifer Ataide • pedido de recompensa</p></div><button type="button" aria-label="Revisar pedido de recompensa" className="rounded-xl bg-white/10 px-3 py-2 text-[10px] font-bold text-white">Revisar</button></div>}{!demoMode && metrics.pendingApprovals === 0 && <div className="p-4 text-sm text-slate-400">Tudo revisado por enquanto.</div>}</Card></div></section>
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><Card className="p-5 sm:col-span-2"><SectionHeading eyebrow="Ritmo da família" title="Taxa semanal" action={<span className="text-xs text-slate-500">Últimos 7 dias</span>} /><div className="mt-5"><div className="mb-2 flex items-center justify-between text-xs"><span className="text-slate-400">Conclusão semanal</span><strong className="text-white">{metrics.weeklyCompletion}%</strong></div><Progress value={metrics.weeklyCompletion} barClassName="from-purple-400 to-cyan-300" /></div></Card><Card className="p-5"><SectionHeading eyebrow="Saúde da base" title="Resumo rápido" /><div className="space-y-4"><div className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-slate-400"><Users size={14} /> Guardiões ativos</span><strong className="text-white">{childList.length}/2</strong></div><Progress value={Math.min(100, childList.length * 50)} barClassName="from-emerald-300 to-cyan-300" /><div className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-slate-400"><Zap size={14} /> XP da família</span><strong className="text-white">{familyXp.toLocaleString("pt-BR")}</strong></div><Progress value={Math.min(100, familyXp / 30)} /><div className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-slate-400"><Shield size={14} /> Moedas guardadas</span><strong className="text-white">{familyCoins}</strong></div></div></Card></section>
  </main>;
}

function ChildAdminCard({ child }: { child: ChildSnapshot }) { const completed = child.missions.filter((mission) => ["completed", "approved"].includes(mission.status)).length; return <Card className="p-5"><div className="flex items-start gap-3"><div className={`grid size-12 place-items-center rounded-2xl text-2xl ${child.experienceMode === "adventure" ? "bg-purple-400/15" : "bg-cyan-300/15"}`}>{child.avatar}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h3 className="font-black text-white">{child.displayName}</h3><span className="text-xs font-bold text-slate-500">Nv. {child.level}</span></div><p className="mt-1 text-xs text-slate-500">{child.experienceMode === "adventure" ? "Modo Aventura" : "Modo Pro"} • streak de {child.currentStreak} dias</p></div></div><div className="mt-5 flex items-center justify-between text-xs"><span className="text-slate-400">Missões hoje</span><strong className="text-white">{completed}/{child.missions.length}</strong></div><Progress value={child.dailyProgress} className="mt-2" /><div className="mt-4 flex items-center justify-between text-[10px] font-semibold text-slate-500"><span>{child.totalXp.toLocaleString("pt-BR")} XP acumulado</span><span className="flex items-center gap-1 text-yellow-200"><Coins size={12} /> {child.coins}</span></div></Card>; }
