"use client";

import { ArrowRight, LockKeyhole, Shield, Sparkles, UserRound } from "lucide-react";
import { motion } from "framer-motion";
import type { Profile } from "@/types/domain";
import { BrandMark } from "@/components/brand-mark";
import { Card } from "@/components/ui/card";
import { ThemeSelector } from "@/components/theme-selector";

export function ProfileSelector({ profiles, onSelect }: { profiles: Profile[]; onSelect: (profile: Profile) => void }) {
  return <main className="mx-auto flex min-h-screen w-full max-w-5xl flex-col px-5 py-8 sm:px-8"><header className="flex items-center justify-between"><BrandMark /><span className="rounded-full border border-white/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">Beta • Base 01</span></header><section className="mx-auto flex w-full max-w-2xl flex-1 flex-col justify-center py-12 sm:py-16"><div className="mb-8 text-center"><motion.div initial={{ scale: .8, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="mx-auto mb-6 grid size-20 place-items-center rounded-[28px] bg-gradient-to-br from-purple-400/25 to-cyan-300/15 text-yellow-200 shadow-[0_0_70px_rgba(155,92,255,.22)]"><Sparkles size={35} /></motion.div><p className="mb-3 text-xs font-black uppercase tracking-[.28em] text-cyan-300">Sua base está chamando</p><h1 className="text-balance text-4xl font-black tracking-[-.04em] text-white sm:text-6xl">Quem está jogando?</h1><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-slate-400">Escolha seu perfil para entrar na missão de hoje.</p></div><div className="mb-8"><ThemeSelector /></div><div className="grid gap-3 sm:grid-cols-3">{profiles.map((profile, index) => <motion.button key={profile.id} initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ delay: index * .08 }} onClick={() => onSelect(profile)} className="text-left"><Card className={`group h-full rounded-[26px] p-5 transition-all hover:-translate-y-1 hover:border-white/30 ${profile.role === "parent" ? "bg-yellow-300/[.05]" : ""}`}><div className="mb-8 flex items-start justify-between"><div className={`grid size-14 place-items-center rounded-2xl text-3xl ${profile.accent === "purple" ? "bg-purple-400/15" : profile.accent === "cyan" ? "bg-cyan-300/15" : "bg-yellow-300/15"}`}>{profile.avatar}</div><ArrowRight className="text-slate-600 transition-transform group-hover:translate-x-1 group-hover:text-white" size={18} /></div><p className="text-lg font-black text-white">{profile.displayName}</p><div className="mt-1 flex items-center gap-2 text-xs text-slate-500">{profile.role === "parent" ? <><Shield size={13} /> Administração</> : <><UserRound size={13} /> {profile.age} anos • {profile.experienceMode === "adventure" ? "Aventura" : "Pro"}</>}</div>{profile.role === "parent" && <div className="mt-6 flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-yellow-200"><LockKeyhole size={12} /> Login seguro</div>}</Card></motion.button>)}</div></section><footer className="flex items-center justify-center gap-2 text-[10px] uppercase tracking-[.16em] text-slate-600"><Shield size={12} /> Uma base. Várias missões. <span className="text-slate-500">v0.1</span></footer></main>;
}
